# Generated by Django 4.1.1 on 2022-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles', models.FloatField()),
                ('avgPace', models.TimeField()),
                ('date', models.DateField()),
                ('additionalNotes', models.TextField(null=True)),
            ],
        ),
    ]
